#!/usr/bin/env python 

## This file was auto-generated by run.py called with the following arguments:
# run.py --whichSim stim_all_model --platform Local --nbcpu 8

## ID string of experiment:
# 2020_10_09_18_13_19_xp000000

## Reproducibility info:
#  platform = Local
#  git commit ID not available
#  Git status not available

thParams =\
{
    "TH_M1_EZ": {
        "connection_info": {
            "thalamic_nucleus_IN": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            },
            "thalamic_nucleus_TC": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            },
            "thalamic_reticular_neucleus_RE": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            }
        },
        "neuro_info": {
            "thalamic_nucleus": {
                "IN": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "I",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 10.0,
                    "n_type_index": 1,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                },
                "TC": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "E",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 20.0,
                    "n_type_index": 0,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                }
            },
            "thalamic_reticular_neucleus": {
                "RE": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "I",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 20.0,
                    "n_type_index": 0,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                }
            }
        },
        "structure_info": {
            "layer_thickness": [
                0.1,
                0.05
            ],
            "region_name": "M1_EZ_th",
            "region_size": [
                1.0,
                1.0,
                0.15
            ],
            "subregion_name": [
                "thalamic_nucleus",
                "thalamic_reticular_neucleus"
            ]
        }
    },
    "TH_M1_IZ": {
        "connection_info": {
            "thalamic_nucleus_IN": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            },
            "thalamic_nucleus_TC": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            },
            "thalamic_reticular_neucleus_RE": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            }
        },
        "neuro_info": {
            "thalamic_nucleus": {
                "IN": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "I",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 10.0,
                    "n_type_index": 1,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                },
                "TC": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "E",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 20.0,
                    "n_type_index": 0,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                }
            },
            "thalamic_reticular_neucleus": {
                "RE": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "I",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 20.0,
                    "n_type_index": 0,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                }
            }
        },
        "structure_info": {
            "layer_thickness": [
                0.1,
                0.05
            ],
            "region_name": "M1_IZ_th",
            "region_size": [
                1.0,
                1.0,
                0.2
            ],
            "subregion_name": [
                "thalamic_nucleus",
                "thalamic_reticular_neucleus"
            ]
        }
    },
    "TH_S1_EZ": {
        "connection_info": {
            "thalamic_nucleus_IN": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            },
            "thalamic_nucleus_TC": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            },
            "thalamic_reticular_neucleus_RE": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            }
        },
        "neuro_info": {
            "thalamic_nucleus": {
                "IN": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "I",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 10.0,
                    "n_type_index": 1,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                },
                "TC": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "E",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 20.0,
                    "n_type_index": 0,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                }
            },
            "thalamic_reticular_neucleus": {
                "RE": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "I",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 20.0,
                    "n_type_index": 0,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                }
            }
        },
        "structure_info": {
            "layer_thickness": [
                0.1,
                0.05
            ],
            "region_name": "S1_EZ_th",
            "region_size": [
                1.0,
                1.0,
                0.15
            ],
            "subregion_name": [
                "thalamic_nucleus",
                "thalamic_reticular_neucleus"
            ]
        }
    },
    "TH_S1_IZ": {
        "connection_info": {
            "thalamic_nucleus_IN": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            },
            "thalamic_nucleus_TC": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            },
            "thalamic_reticular_neucleus_RE": {
                "thalamic_nucleus_IN": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_nucleus_TC": {
                    "delay": 1.0,
                    "p_center": 1.0,
                    "sigma": 0.01,
                    "weight": 1.0
                },
                "thalamic_reticular_neucleus_RE": {
                    "delay": 1.0,
                    "p_center": 0.0,
                    "sigma": 0.01,
                    "weight": 1.0
                }
            }
        },
        "neuro_info": {
            "thalamic_nucleus": {
                "IN": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "I",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 10.0,
                    "n_type_index": 1,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                },
                "TC": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "E",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 20.0,
                    "n_type_index": 0,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                }
            },
            "thalamic_reticular_neucleus": {
                "RE": {
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "I",
                    "I_ex": 15.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 20.0,
                    "n_type_index": 0,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                }
            }
        },
        "structure_info": {
            "layer_thickness": [
                0.1,
                0.05
            ],
            "region_name": "S1_IZ_th",
            "region_size": [
                1.0,
                1.0,
                0.2
            ],
            "subregion_name": [
                "thalamic_nucleus",
                "thalamic_reticular_neucleus"
            ]
        }
    }
}