#!/usr/bin/env python 

## This file was auto-generated by run.py called with the following arguments:
# run.py --whichSim stim_all_model --platform Local --nbcpu 8

## ID string of experiment:
# 2020_10_09_18_13_19_xp000000

## Reproducibility info:
#  platform = Local
#  git commit ID not available
#  Git status not available

connParams =\
{
    "CB_M1_layer_vn": {
        "TH_M1_EZ": {
            "thalamic_nucleus_IN": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.01
            },
            "thalamic_nucleus_TC": {
                "delay": 10.0,
                "p_center": 0.2,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.01
            }
        }
    },
    "M1_L6_CT": {
        "TH_M1_EZ": {
            "thalamic_nucleus_TC": {
                "delay": 10.0,
                "p_center": 0.2,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.01
            },
            "thalamic_reticular_neucleus_RE": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.01
            }
        },
        "TH_M1_IZ": {
            "thalamic_nucleus_TC": {
                "delay": 10.0,
                "p_center": 0.2,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.01
            },
            "thalamic_reticular_neucleus_RE": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.01
            }
        }
    },
    "S1_L6_Pyr": {
        "TH_S1_EZ": {
            "thalamic_nucleus_TC": {
                "delay": 10.0,
                "p_center": 0.2,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.01
            },
            "thalamic_reticular_neucleus_RE": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.01
            }
        },
        "TH_S1_IZ": {
            "thalamic_nucleus_TC": {
                "delay": 10.0,
                "p_center": 0.2,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.01
            },
            "thalamic_reticular_neucleus_RE": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.01
            }
        }
    },
    "TH_M1_EZ": {
        "thalamic_nucleus_TC": {
            "M1_L5B_PT": {
                "delay": 10.0,
                "p_center": 0.2,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            },
            "M1_L5B_PV": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            },
            "M1_L5B_SST": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            }
        }
    },
    "TH_M1_IZ": {
        "thalamic_nucleus_TC": {
            "M1_L5B_PT": {
                "delay": 10.0,
                "p_center": 0.2,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            },
            "M1_L5B_PV": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            },
            "M1_L5B_SST": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            }
        }
    },
    "TH_S1_EZ": {
        "thalamic_nucleus_TC": {
            "S1_L5B_PV": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            },
            "S1_L5B_Pyr": {
                "delay": 10.0,
                "p_center": 0.2,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            },
            "S1_L5B_SST": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            }
        }
    },
    "TH_S1_IZ": {
        "thalamic_nucleus_TC": {
            "S1_L5B_PV": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            },
            "S1_L5B_Pyr": {
                "delay": 10.0,
                "p_center": 0.2,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            },
            "S1_L5B_SST": {
                "delay": 10.0,
                "p_center": 1.0,
                "sigma_x": 0.1,
                "sigma_y": 0.1,
                "weights": 0.1
            }
        }
    }
}